# Spring Boot应用配置
server:
  port: 8082

# 数据源配置 (使用H2内存数据库演示)
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    sql:
      init:
        mode: always
        schema-locations: classpath:data.sql
  
  # H2数据库控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# Mini MyBatis配置
mini:
  mybatis:
    mapper-locations: com.example.demo.mapper
    show-sql: true
    query-timeout: 30

# 日志配置
logging:
  level:
    com.example.mybatis: DEBUG
    com.example.demo: DEBUG
    org.springframework.jdbc: DEBUG 